apiVersion: v1
kind: Pod
metadata:
  name: migrate-django-pro
  labels:
    app: migrate-django-pro
spec:
  containers:
  - name: migrate-django-pro
    image: yangju0411/backend:latest
    #command: ["python", "manage.py", "makemigrations", "&&", "python", "manage.py", "migrate"]
    command: ["bash", "-c"]
    args: ["python manage.py makemigrations && python manage.py migrate"]
    env:
    - name: DJANGO_DB_USER
      valueFrom:
        secretKeyRef:
          name: secret-backend-pro
          key: DJANGO_DB_USER
    - name: DJANGO_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-backend-pro
          key: DJANGO_DB_PASSWORD
     - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-backend-pro
              key: DJANGO_SECRET_KEY
    - name: TZ
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: TZ
    - name: DJANGO_DEBUG
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: DJANGO_DEBUG
    - name: DJANGO_DB_NAME
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: DJANGO_DB_NAME
    - name: DJANGO_DB_HOST
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: DJANGO_DB_HOST
    - name: DJANGO_DB_PORT
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: DJANGO_DB_PORT
    - name: DJANGO_ALLOWED_HOSTS
      valueFrom:
        configMapKeyRef:
          name: config-backend-pro
          key: DJANGO_ALLOWED_HOSTS
  restartPolicy: OnFailure
