version: "3"

services:
  postgre:
    privileged: true
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
  backend:
    privileged: true
    image: p2p:test
    depends_on:
      - postgre
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      #- DATABASE_URL=postgres://postgres:password@postgre:5432/postgres
      - DJANGO_DEBUG=True
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=postgre
      - DJANGO_DB_PORT=5432
#    volumes:
#      - post:/var/lib/postgresql/data
#volumes:
#  post:
