apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-dev
  labels:
    app: frontend-react-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-react-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: frontend-react-dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - frontend-react-dev
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend-react-dev
        image: yangju0411/frontend:00000000
        ports:
          - containerPort: 8080

