apiVersion: v1
kind: Service
metadata:
  name: clusterip-f2b-pro
  labels:
    env: production
spec:
  type: ClusterIP
  selector:
    app: backend-django-pro
    env: production
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
