apiVersion: v1
kind: Service
metadata:
  name: clusterip-f2b-dev
  labels: 
    env: development
spec:
  type: ClusterIP
  selector:
    app: backend-django-dev
    env: development
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
