apiVersion: v1
kind: Service
metadata:
  name: nodeport-frontend-dev
  labels:
    env: development
spec:
  type: NodePort
  selector:
    app: frontend-react
    env: development
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080